### PR TITLE
Squashed commits version of PR#31

### PR DESCRIPTION
**Pull request by yanntm**
I messed up my repo by trying to rebase, let's use this PR instead and close the other one.

### CODE REVIEW

**Comment by alkurbatov** [comment]
Please, add proper subsystem tags to the commits (for full list of the tags see https://github.com/alkurbatov/cpp-sc2/blob/master/.versionrc).
e.g. `feat: Allow to retrieve cloaked enemy units

**Comment by yanntm** [comment]
sorry you need to be more specific, I'm not sure what you mean by this "subsystem tag". 
I suppose I want to tag these commits as `{"type":"build","section":"Build System"}`, or maybe
    `{"type":"docs","section":"Documentation"}`
But what exactly do I tag ? Is it a change to commit messages or something else.

**Comment by alkurbatov** [comment]
The tag should be added to the commit title in form 'tag-name: Message' (from capital letter). When I do release, I'll form changes using special tool from the JS world which lists all commits between git tags (e.g. between 1.0.0 and 1.1.0), parses the titles, extracts subsystem names and group titles by it (see the CHANGELOG file). Thats why I ask to add it.

In this particular case, e.g.:
```
fix: EXCLUDE of */build/* on travis excludes everything
build: Updated travis build script + add Doxygen generation and deployment
```

See the commits in the 1.1.0 release.

**Comment by yanntm** [comment]
ok this rebase was painless at least, please tell me I don't have to sign off on each commit too ;D

**Comment by alkurbatov** [comment]
>ok this rebase was painless at least, please tell me I don't have to sign off on each commit too ;D

Thank you for you patience :)

**Comment by yanntm** [comment]
🍾 👍

**Pull request merged**
