### PR TITLE
Fix get food workers

### PR DESCRIPTION
**Pull request by mboedigh**
fix: GetFoodWorkers() should return uint32_t

### CODE REVIEW

**Comment by alkurbatov** [comment]
Thank you.
Please, resend this PR to master and correct the commit message.

**Comment by mboedigh** [comment]
Ok, I am trying again. Be aware that none of this git fork/pull-request process is clear to me. I am literally spending hours trying to coerce git into doing what I think you want, but it won’t budge. All this for literally 20 seconds of edits to eliminate a single compiler warning. I hoped I would get better but at it, but every pull request has some other problem with it, and I’m having trouble figuring out any standard process that works every time. It would be nice to include a how-to in the contributing guide.

My pull request says it IS already going to alkurbatov/cpp-sc2/master. Rebasing to master has no additional affects.

The commit message already says: ”fix: GetFoodWorkers() should return uint32_t”.
I got that from style that I thought was suggested in .versionrc. Is that incorrect?

I was hoping it would be easy this time because I have other fixes I wanted to push, but was trying to do them “in small, single-issue” style

**Comment by RaphaelRoyerRivard** [comment]
I feel you

**Comment by alkurbatov** [comment]
Guy, you *should* send PRs to the dev branch in order to keep the master stable for other API users. 
Regarding this PR:
Assuming that you have two branches (master and dev):
1. `git log` and take the hash of you commit.
2. git checkout dev
3. git cherry-pick <commit-hash>
4. git commit --amend
And reword the title. 

Which kind of how-to you should be added? So far we have the following: https://github.com/alkurbatov/cpp-sc2/issues/9

**Comment by alkurbatov** [comment]
Sorry, the message is ok. Thats just too many of other commits attached to this PR so I lost the original one.

**Comment by mboedigh** [comment]
My intention is to submit small commits. I didn't realize they were attached to a single PR. 
I will write a what-I-need(or needed)-to-know and someone else can fill in how, because I'm clearly not that person. 
I can't see what is wrong based on the hierarchies below.

My local tree (origin is my fork on github, and upstream is your repository). I tried to isolate a smallfix in FixGetFoodWorkers:
image

My remote (as it is on github. Origin is my fork and upstream is your repository)
image

your remote (cpp-sc2. Origin is yours)
image

**Comment by mboedigh** [comment]
I'm not sure the best place to discuss this, but here is what I needed-to-know when I started (to the best of my recollection, and that I'm aware of). I have questions in []s. 

**Contributing to CPP-SC2**
1)	[Create your own fork](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) of the “upstream” cpp-sc2 repository on github
2)	Create a local copy of the repository on your computer
a.	If you don’t have one, install a git [client ](https://git-scm.com/download/gui/windows)on your computer
b.	[Clone](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork) your repository
c.     [Follow instructions ](https://github.com/alkurbatov/cpp-sc2/blob/master/docs/building.md) to compile and run cpp-sc2.  Several simple bot projects are included. the instructions are not fully up-to-date, but the build can also be made to work with Visual Studio 2019. 
3)	[Configure your local clone ](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork)to sync changes with cpp-sc2 repository
4)	[Create a new branch ](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging)in your local repository to hold your work. [Does this need a feature name, or should it be dev]. Name the branch based on the new feature.
5)	Compile your bot and confirm changes behave as expected
6)	Compile and run tests/all_tests projects that was included in cpp-sc2.
7)	[Commit ](https://guide.freecodecamp.org/git/git-commit/)changes to your local git repository 
a.	Message should explain what was done and why it was necessary
b.	The first line of the commit message should include one of the prefixes from .versionrc in the root of the repository
i.	E.g. “fix: GetFoodWorkers should return uint32_t”
[Do I keep changes on the feature branch or merge to my local dev?]
8)	[Synchronize your clone](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) with the cpp-sc2 (upstream);	
a.	git [fetch ](https://www.atlassian.com/git/tutorials/syncing/git-fetch)upstream
b.	git [checkout ](https://www.atlassian.com/git/tutorials/using-branches/git-checkout)dev. 
c.	git [merge ](https://www.atlassian.com/git/tutorials/using-branches/git-merge)upstream/dev
9)	[Push changes](https://help.github.com/en/github/using-git/pushing-commits-to-a-remote-repository) to your fork (origin) on GitHub
10)	[Create pull request ](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) for cpp-sc2
a.	Automatic checks will be done
b.	Comments can be made
c.	Changes may be suggested
	[how to make changes so they are seamlessly accepted]
d.	After changes are accepted you can optionally [delete your feature branch ](https://www.freecodecamp.org/news/how-to-delete-a-git-branch-both-locally-and-remotely/)
11)	To add additional features make sure the repository is synchronized (#8) and continue with Step 4, for any new features

FAQ:
What if I have several things I’m working on, not all of which may end up in the cpp-sc2?  Is there a pattern for that?

**Comment by alkurbatov** [comment]
Sorry but this is mostly the same as the gut hub documentation. See e.g. https://guides.github.com/introduction/flow/
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

I.e. not the cpp-sc2 specific. Not sure that such detailed guides should be put into contributing.

**Comment by mboedigh** [comment]
// PR
Sorry, to be annoying. I was trying to "Please, resend this PR to master and correct the commit message", which may have been the wrong thing to do. I've resent the PR to dev.
Reading the link you provided I learned pull requests are sent by default to the parent repository's default branch. Would it be helpful to set cpp-sc2's default to dev?

// Contributing guide
That's ok. I don't need my guide now that I've been through this a couple times. I know it is not new material, and I know there are 1000s of how-to-execute this git command pages out there, with bits-and-pieces here and there. I found myself spending a lot of time trying to connect those guides (which cover every use case) to commands that work in specific workflows. Especially if my local repository is complicated. So, my goal was to add the simple but important cpp-sc2 specific material in the right places along with concrete commands a first-timer could follow from beginning to end that a leads to a successful PR. I think that kind of high-level recipe would have helped me avoid mistakes, and I didn't see it anywhere.

I thought the link you provided to github PR was excellent and would be a welcome addition to the contributing guide. Again, it is too general to follow directly because it covers all use cases. In particular, at various points, it instructs people to commit to master, to try to make changes to the parent repository etc. So, it would be great to organize the cpp-sc2 specific information already in the guide, so that it appears in the same context as the link.

  1.  commit message rules
  2.  that Cpp-sc2 uses a fork-and-pull model
  3.  That commits should be sent from a feature branch to the dev branch (which the contributing guide implies, but is different than the github guide)

**Comment by alkurbatov** [comment]
>Sorry, to be annoying.

Thats totally fine, no problem at all.

>Would it be helpful to set cpp-sc2's default to dev?

Unfortunately, this is not a solution. If I do it, the default 'git clone' branch will be the `dev`brunch, too, i.e. all our possible users will get unstable code.


Regarding the guide: I don't mind to add it to the contribution guide, but I assumed that there are a detailed instruction somewhere i.e. we don't need to write and support our own. I have a special issue regarding it https://github.com/alkurbatov/cpp-sc2/issues/42, we can continue discussion there.

**Pull request closed without merging**
